channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  # Load Firefox and corresponding driver from conda-forge.
  - firefox=104.0 # https://anaconda.org/conda-forge/firefox

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==16.3.0 # https://rpaframework.org/releasenotes.html
